### ISSUE TITLE
ADD LEETCODE SOLUTIONS & DSA ALGO IN JAVA

### ISSUE THREAD

**Issue by ruchikayadav1408** [Trinity-Developers-Club/20DOOS_DSA#20]
DSA TOPICS LIKE ARRAY, 2D ARRAY, STRING, BACKTRACKING,SORTING ETC

**Comment by piyush-sri** [comment]
i would like to work on this issue , Please assign this to me.

**Comment by utkr07** [comment]
I would like to add some quality solutions to good Leetcode questions.
